"""
Rolling walk-forward retraining backtest.

Instead of training one static model on historical data, this module
retrains a fresh model every RETRAIN_EVERY_DAYS days using only the
most recent TRAIN_WINDOW_DAYS of data — never peeking at future prices.

Signals generated by each rolling model are accumulated into a single
ticker-data dict, then passed to the same simulation engine used in
backtest.py so the results are directly comparable.
"""

import numpy as np
import pandas as pd
from sklearn.ensemble import RandomForestClassifier

from config import WATCHLIST, FEATURE_COLUMNS, CONFIDENCE_THRESHOLD
from features import load_and_process
from labels import add_labels
from backtest import (
    INITIAL_CAPITAL,
    MAX_POSITION_PCT,
    MAX_TOTAL_EXPOSURE,
    SLIPPAGE,
    COMMISSION,
    load_model,
    load_all_tickers,
    run_backtest,
    _simulate,
)

# --- Rolling window settings ---
TRAIN_WINDOW_DAYS  = 480   # ~18 months of trading days used to train each model
RETRAIN_EVERY_DAYS = 60    # retrain every ~3 months


# ---------------------------------------------------------------------------
# Data helpers
# ---------------------------------------------------------------------------

def _load_raw_data() -> tuple[dict, pd.DataFrame, pd.Series]:
    """
    Load full feature and label data for every ticker.

    Returns:
        raw_data  — ticker -> full featured DataFrame (Close + FEATURE_COLUMNS)
        X_all     — combined feature matrix sorted by date (for training slices)
        y_all     — combined label series sorted by date
    """
    raw_data = {}   # ticker -> featured DataFrame (full history, no labels)
    frames   = []   # labeled DataFrames for building X_all / y_all

    for ticker in WATCHLIST:
        try:
            df = load_and_process(ticker)
            raw_data[ticker] = df

            labeled = add_labels(df)
            frames.append(labeled)
            print(f"[OK]    {ticker} — {len(df)} feature rows, {len(labeled)} labeled")
        except FileNotFoundError:
            print(f"[SKIP]  {ticker} — CSV not found, run data_collector.py first")

    if not frames:
        raise RuntimeError("No data loaded.")

    combined = pd.concat(frames).sort_index()
    return raw_data, combined[FEATURE_COLUMNS], combined["Signal"]


def _fresh_model() -> RandomForestClassifier:
    """Return an untrained RandomForest with the same hyperparameters as trainer.py."""
    return RandomForestClassifier(
        n_estimators=100,       # 100 trees per rolling model keeps runtime fast
        max_depth=10,
        min_samples_leaf=20,
        class_weight="balanced",
        random_state=42,
        n_jobs=-1,
    )


# ---------------------------------------------------------------------------
# Rolling signal generation
# ---------------------------------------------------------------------------

def _generate_rolling_signals(
    raw_data: dict,
    X_all: pd.DataFrame,
    y_all: pd.Series,
    all_dates: list,
) -> tuple[dict, list]:
    """
    Walk forward through time, retraining every RETRAIN_EVERY_DAYS steps.

    For each window:
      - Train on the most recent TRAIN_WINDOW_DAYS of labeled rows
      - Score the next RETRAIN_EVERY_DAYS dates with the new model
      - Store signals in the same format backtest._simulate expects

    Returns:
        ticker_data  — ticker -> DataFrame(Close, Signal, Confidence)
                       covering only dates where predictions were made
        retrain_log  — list of human-readable retrain event strings
    """
    # Accumulate signal rows per ticker before building DataFrames
    sig_rows: dict[str, list] = {t: [] for t in raw_data}
    retrain_log: list[str]    = []
    train_date_set = set(X_all.index)   # dates that have labels (for train filtering)

    retrain_num = 0
    for cycle_start in range(TRAIN_WINDOW_DAYS, len(all_dates), RETRAIN_EVERY_DAYS):
        # --- Define training window ---
        window_start  = max(0, cycle_start - TRAIN_WINDOW_DAYS)
        train_dates   = set(all_dates[window_start:cycle_start])
        train_mask    = X_all.index.isin(train_dates & train_date_set)
        X_train       = X_all[train_mask]
        y_train       = y_all[train_mask]

        if len(X_train) < 100:
            continue   # skip windows with insufficient labeled data

        # --- Define prediction window ---
        pred_end   = min(cycle_start + RETRAIN_EVERY_DAYS, len(all_dates))
        pred_dates = all_dates[cycle_start:pred_end]
        if not pred_dates:
            break

        # --- Train fresh model ---
        model        = _fresh_model()
        model.fit(X_train, y_train)
        model_classes = np.array(model.classes_)

        retrain_num += 1
        train_start_date = all_dates[window_start].strftime("%Y-%m-%d")
        train_end_date   = all_dates[cycle_start - 1].strftime("%Y-%m-%d")
        pred_start_date  = pred_dates[0].strftime("%Y-%m-%d")
        pred_end_date    = pred_dates[-1].strftime("%Y-%m-%d")

        retrain_log.append(
            f"  Retrain #{retrain_num:>2}: trained {train_start_date} to {train_end_date} "
            f"({len(X_train)} rows)  |  predicts {pred_start_date} to {pred_end_date}"
        )

        # --- Score each ticker for the prediction window ---
        pred_date_set = set(pred_dates)
        for ticker, df in raw_data.items():
            df_pred = df[df.index.isin(pred_date_set)]
            if df_pred.empty:
                continue

            X_pred   = df_pred[FEATURE_COLUMNS].values
            proba    = model.predict_proba(X_pred)
            top_idx  = np.argmax(proba, axis=1)
            top_prob = proba[np.arange(len(proba)), top_idx]
            signals  = model_classes[top_idx].copy()
            signals[top_prob < CONFIDENCE_THRESHOLD] = "HOLD"

            for date, close, sig, conf in zip(
                df_pred.index, df_pred["Close"], signals, top_prob
            ):
                sig_rows[ticker].append({
                    "date":       date,
                    "Close":      close,
                    "Signal":     sig,
                    "Confidence": conf,
                })

    # Build DataFrames from accumulated rows
    ticker_data: dict[str, pd.DataFrame] = {}
    for ticker, rows in sig_rows.items():
        if not rows:
            continue
        df = (
            pd.DataFrame(rows)
            .set_index("date")
            .sort_index()
        )
        ticker_data[ticker] = df

    return ticker_data, retrain_log


# ---------------------------------------------------------------------------
# Rolling backtest summary stats (mirrors backtest._simulate return processing)
# ---------------------------------------------------------------------------

def _compute_stats(trade_log: list, equity_curve: list, label: str) -> dict:
    """Compute the same summary statistics reported by backtest.run_backtest."""
    equity_df   = pd.DataFrame(equity_curve).set_index("date")
    final_value = float(equity_df["portfolio_value"].iloc[-1]) if equity_curve else INITIAL_CAPITAL
    n_trades    = len(trade_log)
    returns     = [t["trade_return"] for t in trade_log]

    if n_trades > 0:
        win_rate    = len([r for r in returns if r > 0]) / n_trades * 100
        avg_return  = float(np.mean(returns)) * 100
        best_trade  = max(returns) * 100
        worst_trade = min(returns) * 100
    else:
        win_rate = avg_return = best_trade = worst_trade = 0.0

    pv           = equity_df["portfolio_value"]
    max_drawdown = float(((pv - pv.cummax()) / pv.cummax() * 100).min()) if len(pv) > 1 else 0.0
    total_return = (final_value - INITIAL_CAPITAL) / INITIAL_CAPITAL * 100

    dates      = equity_df.index
    date_range = f"{dates[0].strftime('%Y-%m-%d')} to {dates[-1].strftime('%Y-%m-%d')}" if len(dates) else "N/A"

    return {
        "label":        label,
        "date_range":   date_range,
        "n_days":       len(equity_curve),
        "final_value":  final_value,
        "total_return": total_return,
        "n_trades":     n_trades,
        "win_rate":     win_rate,
        "avg_return":   avg_return,
        "best_trade":   best_trade,
        "worst_trade":  worst_trade,
        "max_drawdown": max_drawdown,
        "equity_df":    equity_df,
    }


# ---------------------------------------------------------------------------
# Main entry point
# ---------------------------------------------------------------------------

def run_rolling_backtest() -> dict:
    """
    Execute the rolling walk-forward backtest and return summary statistics.

    Also prints a retrain event log and a comparison table against the
    static-model full-period backtest from backtest.py.
    """
    print("=== Loading raw feature and label data ===")
    raw_data, X_all, y_all = _load_raw_data()

    all_dates = sorted(set().union(*[set(df.index) for df in raw_data.values()]))
    print(f"\nTotal unique trading dates : {len(all_dates)}")
    print(f"Train window               : {TRAIN_WINDOW_DAYS} days")
    print(f"Retrain every              : {RETRAIN_EVERY_DAYS} days")
    print(f"First prediction starts at : day {TRAIN_WINDOW_DAYS} "
          f"({all_dates[TRAIN_WINDOW_DAYS].strftime('%Y-%m-%d')})")

    print("\n=== Generating rolling signals ===")
    ticker_data, retrain_log = _generate_rolling_signals(raw_data, X_all, y_all, all_dates)

    print(f"\nModel was retrained {len(retrain_log)} time(s):")
    for entry in retrain_log:
        print(entry)

    print("\n=== Running rolling simulation ===")
    sim_dates  = sorted(set().union(*[set(df.index) for df in ticker_data.values()]))
    trade_log, equity_curve = _simulate(sim_dates, ticker_data)
    rolling_stats = _compute_stats(trade_log, equity_curve, "Rolling retrain")

    # Save equity curve
    rolling_stats["equity_df"].to_csv("rolling_backtest_results.csv")
    print("Rolling equity curve saved to rolling_backtest_results.csv")

    # --- Static model comparison (full-period, same data) ---
    print("\n=== Running static model backtest for comparison ===")
    static_model  = load_model()
    static_td     = load_all_tickers(static_model)
    static_result = run_backtest("full", model=static_model, ticker_data=static_td)

    static_stats = {
        "label":        "Static model",
        "date_range":   static_result["date_range"],
        "n_days":       static_result["n_days"],
        "final_value":  static_result["final_value"],
        "total_return": static_result["total_return"],
        "n_trades":     static_result["n_trades"],
        "win_rate":     static_result["win_rate"],
        "avg_return":   static_result["avg_return"],
        "best_trade":   static_result["best_trade"],
        "worst_trade":  static_result["worst_trade"],
        "max_drawdown": static_result["max_drawdown"],
    }

    # --- Comparison table ---
    div = "=" * 82
    sep = "-" * 82
    print(f"\n{div}")
    print(f"  STATIC MODEL  vs.  ROLLING RETRAIN  —  COMPARISON")
    print(div)
    metrics = [
        ("Date range",       "date_range",   "{:<25}",  "{:<25}"),
        ("Trading days",     "n_days",       "{:>10}",  "{:>10}"),
        ("Final value",      "final_value",  "${:>10,.2f}", "${:>10,.2f}"),
        ("Total return",     "total_return", "{:>+10.2f}%", "{:>+10.2f}%"),
        ("Trades",           "n_trades",     "{:>10}",  "{:>10}"),
        ("Win rate",         "win_rate",     "{:>10.1f}%",  "{:>10.1f}%"),
        ("Avg trade return", "avg_return",   "{:>+10.2f}%", "{:>+10.2f}%"),
        ("Best trade",       "best_trade",   "{:>+10.2f}%", "{:>+10.2f}%"),
        ("Worst trade",      "worst_trade",  "{:>+10.2f}%", "{:>+10.2f}%"),
        ("Max drawdown",     "max_drawdown", "{:>+10.2f}%", "{:>+10.2f}%"),
    ]

    col = 22
    print(f"  {'Metric':<{col}}  {'Static model':>18}  {'Rolling retrain':>18}")
    print(sep)
    for label, key, fmt_s, fmt_r in metrics:
        sv = static_stats[key]
        rv = rolling_stats[key]
        s_str = fmt_s.format(sv)
        r_str = fmt_r.format(rv)
        print(f"  {label:<{col}}  {s_str:>18}  {r_str:>18}")

    print(div)
    print(f"  Rolling model retrained {len(retrain_log)}x "
          f"(every ~{RETRAIN_EVERY_DAYS} days, "
          f"{TRAIN_WINDOW_DAYS}-day train window)")
    print(div)

    return rolling_stats


if __name__ == "__main__":
    run_rolling_backtest()
